# Generated by Django 2.0.1 on 2018-10-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
